#!/usr/local/bin/bash

# normal sources, pmc stuff added manually in debug command
SOURCES="src/main.c src/gfx/gfx.c src/vm/vm.c src/programs/linedraw.c src/programs/manylines.c src/programs/boxdraw.c src/programs/emitters.c"



# without pmc
cc --std=c23 -Wall -Werror -Wno-gnu-label-as-value -pedantic    \
  -I/usr/local/include \
  -L/usr/local/lib \
  $SOURCES \
  -lpng \
  -pthread \
  $(pkg-config --cflags --libs sdl3) \
  -g \
  -o cgvm.elf

# strict debug command generated by chatgpt... (yikes!) (has asan/ubsan)
cc --std=c23                                          \
  -O2                                                 \
  -Wall                                               \
  -Wextra                                             \
  -Wpedantic                                          \
  -Werror                                             \
  -Wshadow                                            \
  -Wconversion                                        \
  -Wsign-conversion                                   \
  -Wcast-qual                                         \
  -Wwrite-strings                                     \
  -Wstrict-prototypes                                 \
  -Wmissing-prototypes                                \
  -Wundef                                             \
  -Wformat=2                                          \
  -Wswitch-enum                                       \
  -Wimplicit-fallthrough                              \
  -Wnull-dereference                                  \
  -Wdouble-promotion                                  \
  -Wcast-align                                        \
  -Wno-gnu-label-as-value                             \
  -fstack-protector-strong                            \
  -fno-omit-frame-pointer                             \
  -fsanitize=address,undefined                        \
  -I/usr/local/include                                \
  -L/usr/local/lib                                    \
   $SOURCES \
   src/vm/pmc_wrap.c \
  -lpng                                               \
  -lpmc \
  -pthread \
  $(pkg-config --cflags --libs sdl3) \
  -DDO_PMC \
  -o cgvm-pmc.elf
